### ISSUE TITLE
Does your code work? Something went wrong please try again

### ISSUE THREAD

**Issue by armornet** [SauravKanchan/CodeCheck#38]
Hi,
   I was testing your compiler every time i write a code it shows 

Something went wrong please try again

Help needed..

**Comment by SauravKanchan** [comment]
Hi armornet,
I am not maintaining this repository anymore. As you can see the last commit was 2 years old. I was using Hackerrank API for the compiler and now hackerrank has removed that API. After this project, I made a new [website](https://codehash.co/) for one of my clients, we are using [judge0](https://github.com/judge0/api) for this project.

**Comment by armornet** [comment]
Ok so you mean now your charge for new api.. Ok then how much charge for i want host it on my server... I also sent you email regarding this.. but you haven't yet replied me

**Comment by SauravKanchan** [comment]
Sorry for late reply. We don't charge for API we are running [Judge0](https://github.com/judge0/api) on our servers. If you want to use the API then I will suggest you to use judge0
